export const BLOCK = {
  PARAGRAPH: "Paragraph",
  HEADER: "",
  HEADERMARK: "HeaderMark",
  BLOCKQUOTE: "Blockquote",
  QUOTEMARK: "QuoteMark",
  FENCEDCODE: "FencedCode",
  CODEMARK: "CodeMark",
  CODEINFO: "CodeInfo",
  CODETEXT: "CodeText",
  BULLETLIST: "BulletList",
  ORDEREDLIST: "OrderedList",
  LISTITEM: "ListItem",
  LISTMARK: "ListMark",
  TASK: "Task",
  TASKMARKER: "TaskMarker",
  HORIZONTALRULE: "HorizontalRule",
};

export const STYLE = {
  BOLD: "cm-bold",
  ITALIC: "cm-italic",
  INLINECODE: "cm-inlinecode",
  STRIKE: "cm-strike",
  SUPER: "cm-super",
  SUB: "cm-sub",
  IMAGE: "cm-image",
  INTERNALLINK: "cm-internal-link",
  LINK: "cm-link",
  QUOTE: "cm-quote",
  BLOCKQUOTE_AREA: "cm-blockquote-area",
  BLOCKQUOTE_FIRST: "cm-blockquote-first",
  BLOCKQUOTE_LAST: "cm-blockquote-last",
  BLOCKQUOTE: "cm-blockquote",
  HEADING: "cm-heading",
  H1: "cm-h1",
  H2: "cm-h2",
  H3: "cm-h3",
  H4: "cm-h4",
  H5: "cm-h5",
  H6: "cm-h6",
  FENCEDCODE_AREA: "cm-fencedcode-area",
  FENCEDCODE_FIRST: "cm-fencedcode-first",
  FENCEDCODE_LAST: "cm-fencedcode-last",
  CODEMARK: "cm-codemark",
  CODEINFO: "cm-codeinfo",
  CODETEXT: "cm-codetext",
  LIST_AREA: "cm-list-area",
  LIST_MARK: "cm-list-mark",
  LIST_DEPTH_PREFIX: "cm-list-depth-",
  BULLET_LIST_MARK: "cm-bullet-list-mark",
  ORDERED_LIST_MARK: "cm-ordered-list-mark",
  TASK_MARKER: "cm-task-marker",
  COMPLETED_TASK: "cm-completed-task",
  TASK_TEXT: "cm-task-text",
  HR_LINE: "cm-hr", // New
};

export const HIDE = "hide";

export const INLINE = {
  BOLD: "",
  ITALIC: "",
  URL: "URL",
};
